sonar.projectKey=school-grade-predictor
sonar.projectName=School Grade Predictor
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**
